### ISSUE TITLE
Docs are out of date

### ISSUE THREAD

**Issue by kennyb5000** [asanghi/fiscali#10]
Under [Using in your rails project](https://github.com/asanghi/fiscali#using-in-your-rails-project) it says:

```
Date.fiscal_zone = :india
Time.fiscal_zone = :india
or Date.start_month = 4
```

When setting it manually I had to use:
`Date.fy_start_month=4`

It may also be worth noting that you have to set it for each class Date, Time, and DateTime, so my initializer looks like:

```
Date.fy_start_month = 2
Time.fy_start_month = 2
DateTime.fy_start_month = 2
```

**Comment by maxwell** [comment]
This should be fixed now!
