### ISSUE TITLE
Add configuration for fiscal year start week

### ISSUE THREAD

**Issue by moubry** [asanghi/fiscali#15]
I love that you have a configuration for `start_month`. However, it would also be nice to have a similar configuration for `start_week`, because some companies start their fiscal years in the middle of the month — for example, the 4th week of a month.

Start week would be an integer ranging from 1–5. By default it would be 1, since most companies start their fiscal year in the first week of the month.

I quickly spiked-out a working version of this change here: https://github.com/moubry/fiscali/commit/9121ba2878b5a0b6b1349aa947f5b164e32d9e10. Tests pass.

**Comment by asanghi** [comment]
Happy to include! Please send PR!

**Comment by maxwell** [comment]
If you still require this, please submit a PR.  Closing out for now!
