### ISSUE TITLE
Dependency on ActiveSupport

### ISSUE THREAD

**Issue by MikeFlint** [asanghi/fiscali#20]
Hi,

I'm using your gem in a Sinatra application, and don't have (nor want to install) ActiveSupport.

If I comment out the two ActiveSupport 'requires' in fiscali/lib/fiscali.rb everything appears to work for me, so should ActiveSupport be in the gemspec (and fiscali.rb)?

Mike.

**Comment by asanghi** [comment]
The gem uses a bunch of methods from `activesupport`. The reason you do not seem to have a problem is because the methods that depend on `activesupport` might not be invoked in how you are using the functions.

**Comment by MikeFlint** [comment]
Thanks. I see them now.
