### ISSUE TITLE
Wrong fiscal_year_start

### ISSUE THREAD

**Issue by ddnexus** [asanghi/fiscali#23]
I found an inconsistency and potential bug in the gem:

```ruby
>> Date.fiscal_zone
:us
>> Date.uses_forward_year?
true
>> Date.today
Mon, 08 Oct 2018
>> Date.today.financial_year
2019
>> Date.financial_year_start
Mon, 01 Oct 2018
>> Date.financial_year_start(2019)
Tue, 01 Oct 2019
```

The last statement returns a wrong result. The `financial_year_start` of 2019 should be `Mon, 01 Oct 2018` not `Tue, 01 Oct 2019`.

**Comment by ddnexus** [comment]
No idea about why it is wrong... I should look and understand the code first. Maybe it is not considering the forward year? If you know how to fix it, I would certainly trust more your change than mine. :)

**Comment by asanghi** [comment]
most definitely its because not recognizing the forward year.
I havent needed this gem for many years and currently busy elsewhere. If im going to get involved, it could take a long time.

**Comment by ddnexus** [comment]
see #9!

**Comment by maxwell** [comment]
This has been fixed by: https://github.com/asanghi/fiscali/pull/32  thanks @wubr !!
