### ISSUE TITLE
What is the link for CI?

### ISSUE THREAD

**Issue by maxwell** [asanghi/fiscali#28]
Is CI set up for this project? If not, could I set one up?

**Comment by maxwell** [comment]
I set up github actions to run on the most recent ruby... but if there is an old travis I can use that too.

**Comment by asanghi** [comment]
Might be worth setting up travis. If the travis.yml is missing then I’m mistaken about having put it in place.

**Comment by maxwell** [comment]
It looks like we have a Travis.yml but I couldn’t find a page. 

- maxwell

**Comment by asanghi** [comment]
Could be a travis version issue? Perhaps I need to give special access on travis? I hope you work it out, if not I’ll assist Max

**Comment by maxwell** [comment]
Looks like according to Travis I do not have the requisite rights to tweak the settings

- maxwell
