### ISSUE TITLE
Can we get a new version cut?

### ISSUE THREAD

**Issue by maxwell** [asanghi/fiscali#30]
Either a) can we get a new gem release or b) Can i get added to release a new version?

Thank you.

**Comment by asanghi** [comment]
a) Absolutely
b) I’ll add you to rubygems account

Many thanks!

**Comment by asanghi** [comment]
I need your handle on rubygems to add you as an owner to the release account @maxwell

**Comment by maxwell** [comment]
My rubygems email is: maxwell@joindiaspora.com
